draw:
  background: '#e1eeb0'
  fill: 25
  noStroke: null
  rect:
    - [gameEdgeRight, 0, 150, height]
    - [0, 0, gameEdgeLeft, height]
    - [450, 80, 150, 70]
    - [460, 405, 130, 130, 5]
    - [460, 210, 130, 60, 5]
    - [460, 280, 130, 60, 5]
    - [450, 85, 150, 20]
    - [450, 110, 150, 4]
    - [450, 140, 150, 4]
    - [460, 60, 130, 35, 5]
    - [465, 65, 120, 25, 5]
    - [465, 410, 120, 120, 5]
    - [465, 215, 120, 50, 5]
    - [465, 285, 120, 50, 5]
  fill: 25
  noStroke: null
  textSize: 24
  textAlign: CENTER
  text: ["Score", 525, 85]
  text: ["Level", 525, 238]
  text: ["Lines", 525, 308]
  fill: 255
  noStroke: null
  textSize: 24
  textAlign: RIGHT
  text: [currentScore, 560, 135]
  text: [currentLevel, 560, 260]
  text: [linesCleared, 560, 330]
  stroke: '#0d0d0d'
  line: [gameEdgeRight, 0, gameEdgeRight, height]
  fallingPiece.show
  if:
    keyIsDown: DOWN_ARROW
  else:
    updateEvery: updateEveryCurrent
  if:
    not: pauseGame
    then:
      ticks: ['+=', 1]
      if:
        '===': [ticks, updateEvery]
        then:
          ticks: 0
          fallingPiece.fall: fallSpeed
  for: {i: 0, condition: "<", length: gridPieces.length, step: 1}
    gridPieces[i].show
  for: {i: 0, condition: "<", length: lineFades.length, step: 1}
    lineFades[i].show
  if: ['>', gridWorkers.length, 0]
    gridWorkers[0].work
  textAlign: CENTER
  fill: 255
  noStroke: null
  textSize: 14
  text: |
    Controls:
    ↑
    ← ↓ →
    Left and Right:
    move side to side
    Up:
    rotate
    Down:
    fall faster
    R:
    reset game
  if: gameOver
    then:
      fill: '#0d0d0d'
      textSize: 54
      textAlign: CENTER
      text: "Game Over!", [300, 270]
  strokeWeight: 3
  stroke: '#304550'
  noFill: null
  rect: [0, 0, width, height]
